name: Doxygen Action

# Run action after every push to master branch
on:
  push:
    branches: [ main ]

# The actual doxygen job to run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout repository
    - uses: actions/checkout@v2
      # run doxygen
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.12.0
      with:
        doxyfile-path: "./.github/doxyfile"
        working-directory: "."
      # deploy documentation as github page
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/html
